spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/departments?useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Opethodamsam99
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

logging:
  level:
    root: debug

